"""Tests for mcpower_gui.script_generator — generate_script output."""

from mcpower_gui.script_generator import generate_script
from mcpower_gui.state import ModelState


def _minimal_state(**overrides) -> dict:
    """Return a minimal ModelState snapshot with optional overrides."""
    state = ModelState(formula="y = x1 + x2", effects={"x1": 0.5, "x2": 0.3})
    snap = state.snapshot()
    snap.update(overrides)
    return snap


def _minimal_params(**overrides) -> dict:
    params = {"sample_size": 100, "target_test": "all"}
    params.update(overrides)
    return params


class TestGenerateScriptHeader:
    def test_version_and_citation_header(self):
        script = generate_script(_minimal_state(), _minimal_params(), mode="power")
        assert "# Generated by MCPower v" in script
        assert "# Cite: Lenartowicz" in script

    def test_header_before_imports(self):
        script = generate_script(_minimal_state(), _minimal_params(), mode="power")
        header_pos = script.index("# Generated by MCPower")
        import_pos = script.index("from mcpower import MCPower")
        assert header_pos < import_pos


class TestGenerateScriptPowerMode:
    def test_minimal_power(self):
        script = generate_script(_minimal_state(), _minimal_params(), mode="power")
        assert "from mcpower import MCPower" in script
        assert 'MCPower("y = x1 + x2")' in script
        assert "find_power(" in script
        assert "sample_size=100" in script
        assert 'set_effects("x1=0.5, x2=0.3")' in script

    def test_no_csv_without_data(self):
        script = generate_script(_minimal_state(), _minimal_params(), mode="power")
        assert "import csv" not in script
        assert "upload_data" not in script


class TestGenerateScriptSampleSizeMode:
    def test_sample_size_mode(self):
        params = _minimal_params(ss_from=30, ss_to=200, ss_by=10)
        script = generate_script(_minimal_state(), params, mode="sample_size")
        assert "find_sample_size(" in script
        assert "from_size=30" in script
        assert "to_size=200" in script
        assert "by=10" in script


class TestGenerateScriptWithData:
    def test_data_file_path(self):
        script = generate_script(
            _minimal_state(),
            _minimal_params(),
            mode="power",
            data_file_path="/tmp/data.csv",
        )
        assert "import csv" in script
        assert "csv.DictReader" in script
        assert "/tmp/data.csv" in script
        assert "upload_data(data" in script


class TestGenerateScriptVariableTypes:
    def test_variable_types_included(self):
        state = _minimal_state(
            variable_types={"x1": {"type": "binary", "proportion": 0.5}}
        )
        script = generate_script(state, _minimal_params(), mode="power")
        assert "set_variable_type(" in script
        assert "binary" in script


class TestGenerateScriptCorrelations:
    def test_correlations_included(self):
        state = _minimal_state(correlations={"x1,x2": 0.4})
        script = generate_script(state, _minimal_params(), mode="power")
        assert "set_correlations(" in script
        assert "corr(x1, x2)=0.4" in script


class TestGenerateScriptClusterConfigs:
    def test_random_intercept(self):
        state = _minimal_state(
            formula="y ~ x1 + (1|school)",
            cluster_configs=[
                {"grouping_var": "school", "ICC": 0.2, "n_clusters": 20}
            ],
        )
        script = generate_script(state, _minimal_params(), mode="power")
        assert 'set_cluster("school"' in script
        assert "ICC=0.2" in script
        assert "n_clusters=20" in script

    def test_random_slope(self):
        state = _minimal_state(
            formula="y ~ x1 + (1 + x1|school)",
            cluster_configs=[
                {"grouping_var": "school", "ICC": 0.2, "n_clusters": 20,
                 "random_slopes": ["x1"], "slope_variance": 0.1,
                 "slope_intercept_corr": 0.3}
            ],
        )
        script = generate_script(state, _minimal_params(), mode="power")
        assert 'set_cluster("school"' in script
        assert "random_slopes=" in script
        assert "slope_variance=0.1" in script
        assert "slope_intercept_corr=0.3" in script

    def test_nested_effects(self):
        state = _minimal_state(
            formula="y ~ x1 + (1|school/classroom)",
            cluster_configs=[
                {"grouping_var": "school", "ICC": 0.15, "n_clusters": 10},
                {"grouping_var": "school:classroom", "ICC": 0.10, "n_per_parent": 3},
            ],
        )
        script = generate_script(state, _minimal_params(), mode="power")
        assert 'set_cluster("school"' in script
        assert 'set_cluster("school:classroom"' in script
        assert "n_per_parent=3" in script

    def test_no_clusters_no_set_cluster(self):
        script = generate_script(_minimal_state(), _minimal_params(), mode="power")
        assert "set_cluster" not in script
